baseURL = 'https://nostick.fr/'
languageCode = 'fr-fr'
title = 'Nostick'
theme = 'hugo-flex'
favicon = 'favicon.ico'
defaultContentLanguage = "fr"

[languages]
  [languages.fr]
    languageName = 'French'
    weight = 1

[taxonomies]
  tag = "tags"

enableRobotsTXT = false

[permalinks]
  actu = "/actu/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["html"]
    mediaType = "text/html"
  [mediaTypes."application/rss"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    baseName = "index"
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "index"
    isPlainText = true
    isHTML = false
