baseURL = 'https://nostick.fr/'
languageCode = 'fr-fr'
title = 'Nostick'
theme = 'hugo-flex'
favicon = 'favicon.ico'
defaultContentLanguage = "fr"

[languages]
[languages.fr]
languageName = 'French'
weight = 1

[taxonomies]
tag = "tags"
enableRobotsTXT = true

[permalinks]
actu = "/actu/:slug/"

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

[mediaTypes]
[mediaTypes."text/html"]
suffixes = ["html"]
mediaType = "text/html"

[mediaTypes."application/rss+xml"]
suffixes = ["xml"]
mediaType = "application/rss+xml"

[outputFormats]
[outputFormats.HTML]
mediaType = "text/html"
baseName = "index"

[outputFormats.RSS]
baseName = "feed"
mediaType = "application/rss+xml"
isPlainText = true
isHTML = false
