baseURL = 'https://nostick.fr/'
languageCode = 'fr-fr'
title = 'Nostick'
theme = 'hugo-flex'
favicon = 'favicon.ico'
defaultContentLanguage = "fr"
[languages]
  [languages.fr]
    languageName = 'French'
    weight = 1
[taxonomies]
  tag = "tags"
enableRobotsTXT = false
[rss]
  url = "https://nostick.fr/feed.xml"